### ISSUE TITLE
一个☝️状态管理的小问题

### ISSUE THREAD

**Issue by ghost** [huang-weilong/d9l_weather#1]
HomePage的BackgroundColor在Theme发生更改之后不会强制重绘。
请教一下有什么解决方法吗？

**Comment by huang-weilong** [comment]
`context`从外部传递进来，不使用原代码中的`navigatorKey.currentContext`

**Comment by matthewalan0** [comment]
如果可以，能麻烦大佬详细说说吗，谢谢
________________________________

**Comment by ghost** [comment]
> `context`从外部传递进来，不使用原代码中的`navigatorKey.currentContext`

可以麻烦大佬详细说一说吗，谢谢🙏

**Comment by ghost** [comment]
已解决。
将Change Theme界面的Appbar的返回按钮自定义点击事件为：
```
Navigator.pop(context,Provider.of<Themes>(context, listen: false));
```
在Home Page中改成：
```
Navigator.push(context, CupertinoPageRoute(builder: (_) => ChangeThemePage())).then((result) {
     setState(() {
     });
});
```
